workflows:
  ios-release:
    name: iOS Release
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier: com.sai.helloApp
      groups:
        -ios 
      flutter: stable
      xcode: latest
    integrations:
      app_store_connect: Codemagic  
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ipa --release --no-codesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key: $APP_STORE_API_KEY
        key_id: $APP_STORE_KEY_ID
        issuer_id: $APP_STORE_ISSUER_ID
        submit_to_testflight: true
        
