workflows:
  ios-release:
    name: iOS Release
    environment:
      flutter: stable
      xcode: latest
    integrations:
      app_store_connect: Codemagic  
    scripts:
      - name: Get dependencies
        script: flutter pub get
      - name: Build iOS
        script: flutter build ipa --release --nocodesign
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        
