workflows:
  ios-release:
    name: iOS Release Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      vars:
        APP_ID: "com.sai.helloApp" # <-- update if needed
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get

      - name: Build IPA for release
        script: flutter build ipa --release

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: 
          key_id: R9B224UPGS
          issuer_id: 9b674f34-b80b-45dc-87b0-a26e391538da
          key: |
            -----BEGIN PRIVATE KEY-----
            MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgs2NxOaVtqQ83J8od
            BRuinFjmSxP0OhbOahk2KV05fomgCgYIKoZIzj0DAQehRANCAARcWfSouJZVLNWT
            lWMGAs6CjVrVwlo5eZXfEuXjb1DtZoYiFD9UFfHBmspsJ6Ft0SvnZ/fheMu0ON8X
            Hee+GwKy
            -----END PRIVATE KEY-----
        submit_to_testflight: true
