workflows:
  ios-release:
    name: iOS Release Workflow
    environment:
      groups:
        - app_store_credentials
      flutter: stable
      xcode: latest
      cocoapods: default
    scripts:
      - name: Get Flutter dependencies
        script: flutter pub get
      - name: Build IPA for release
        script: flutter build ipa --release
    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        api_key:
          key_id: $APP_STORE_KEY_ID
          issuer_id: $APP_STORE_ISSUER_ID
          key: $APP_STORE_API_KEY
        submit_to_testflight: true
